/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef BMGAMEANALYTICS_AUTODEFS_H
#define BMGAMEANALYTICS_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_BMGAMEANALYTICS_NAME "bmGameAnalytics"
#define S3E_EXT_BMGAMEANALYTICS_HASH 0x7ead316

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("bmGameAnalytics", 15)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !BMGAMEANALYTICS_AUTODEFS_H */
