/*
 * (C) 2001-2012 Marmalade. All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Marmalade.
 *
 * This file consists of source code released by Marmalade under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_BMGAMEANALYTICS_H
#define S3E_EXT_BMGAMEANALYTICS_H

#include <s3eTypes.h>

enum bmGameAnalyticsResourceFlowType 
{
    bmGameAnalyticsResourceFlowTypeSource = 1,
    bmGameAnalyticsResourceFlowTypeSink = 2
};

enum bmGameAnalyticsProgressionStatus 
{
    bmGameAnalyticsProgressionStatusStart = 1,
    bmGameAnalyticsProgressionStatusComplete = 2,
    bmGameAnalyticsProgressionStatusFail = 3
};

enum bmGameAnalyticsErrorSeverity 
{
    bmGameAnalyticsErrorSeverityDebug = 1,
    bmGameAnalyticsErrorSeverityInfo = 2,
    bmGameAnalyticsErrorSeverityWarning = 3,
    bmGameAnalyticsErrorSeverityError = 4,
    bmGameAnalyticsErrorSeverityCritical = 5
};

enum bmGameAnalyticsError
{
    S3E_BMGAMEANALYTICS_ERR_NONE = 0,
    S3E_BMGAMEANALYTICS_ERR_PARAM = 1,
    S3E_BMGAMEANALYTICS_ERR_UNAVAIL = 5,
    S3E_BMGAMEANALYTICS_ERR_CONFIG = 1000,
};
// \cond HIDDEN_DEFINES
S3E_BEGIN_C_DECL
// \endcond

/**
 * Returns S3E_TRUE if the bmGameAnalytics extension is available.
 */
s3eBool bmGameAnalyticsAvailable();

/**
 * Retrieves the last error as a string, if any, for this subdevice. This
 * function is only available in debug builds.
 * @see bmGameAnalyticsGetError
 *
 * @remark This function, as opposed to bmGameAnalyticsGetError(), will always
 * return the last error no matter how many times it is called. This function
 * should not be relied upon to indicate whether an error has just occurred.
 *
 * @par Required Header Files
 * bmGameAnalytics.h
 */
const char* bmGameAnalyticsGetErrorString();

/**
 * Retrieves the last error, if any, for this subdevice.
 * @see bmGameAnalyticsGetErrorString
 *
 * @remark Calling this function will retrieve the last error and then remove
 * it from memory; therefore, any further calls to this function will not
 * return an error unless a subsequent error has occurred.
 *
 * @par Required Header Files
 * bmGameAnalytics.h
 */
bmGameAnalyticsError bmGameAnalyticsGetError();

/*!
 @method

 @abstract Add new business event

 @param currency
    Currency code in ISO 4217 format. (e.g. USD)
 @param amount
    (Integer) Amount in cents. (e.g. 99)
 @param itemType
    Item Type bought. (e.g. Gold Pack)
 @param itemId
    Item bought. (e.g. 1000 gold)
 @param receipt
    Transaction receipt string. (Optional, can be nullptr)
	If receipt is null, then in IOS7+ SDK will try to retrieve the receipt automatically when called directly after a successful in-app purchase.

 @availability Available since 1.0.0

 @attribute Note! This method cannot be called before initialize method has been triggered
 */
void bmGameAnalyticsAddBusinessEvent(const char * currency, int amount, const char * itemType, const char * itemId, const char * cartType, const char * receipt S3E_DEFAULT(NULL));

/*!
 @method

 @abstract Add new resource event

 @param flowType
    Add or substract resource.<br> (See. bmGameAnalyticsResourceFlowType)
 @param currency
    One of the available currencies set in configureAvailableResourceCurrencies
 @param amount
    Amount sourced or sinked
 @param itemType
    One of the available currencies set in configureAvailableResourceItemTypes
 @param itemId
    Item id (string max length=32)

 @availability Available since 2.0.0

 @attribute Note! This method cannot be called before initialize method has been triggered
 */
void bmGameAnalyticsAddResourceEvent(bmGameAnalyticsResourceFlowType flowType, const char * currency, int amount, const char * itemType, const char * itemId);

/*!
 @method

 @abstract Add new progression event

 @param progressionStatus
    Status of added progression.<br> (See. bmGameAnalyticsProgressionStatus)
 @param progression01
    1st progression (e.g. world01)
 @param progression02
    2nd progression (e.g. level01)
 @param progression03
    3rd progression (e.g. phase01)

 @availability Available since 1.0.0

 @attribute Note! This method cannot be called before initialize method has been triggered
 */
void bmGameAnalyticsAddProgressionEventWithScore(bmGameAnalyticsProgressionStatus progressionStatus, const char * progression01, const char * progression02, const char * progression03, int score);

void bmGameAnalyticsAddProgressionEvent(bmGameAnalyticsProgressionStatus progressionStatus, const char * progression01, const char * progression02, const char * progression03);

/*!
 @method

 @abstract Add new design event without a value

 @param eventId
    String can consist of 1 to 5 segments.<br>
    Segments are seperated by ':' and segments can have a max length of 32.<br>
    (e.g. segment1:anotherSegment:gold)

 @availability Available since 2.0.0

 @attribute Note! This method cannot be called before initialize method has been triggered
 */
void bmGameAnalyticsAddDesignEvent(const char * eventId);

/*!
 @method

 @abstract Add new design event with a value

 @param eventId
    String can consist of 1 to 5 segments.<br>
    segments are seperated by ':' and segments can have a max length of 32.<br>
    (e.g. segment1:anotherSegment:gold)
 @param value
    Number value of event

 @availability Available since 2.0.0

 @attribute Note! This method cannot be called before initialize method has been triggered
 */
void bmGameAnalyticsAddDesignEventWithValue(const char * eventId, int value);

/*!
 @method

 @abstract Add new error event

 @param severity
    Severity of error (See. bmGameAnalyticsErrorSeverity)
 @param message
    Error message (Optional, can be nil)

 @availability Available since 2.0.0

 @attribute Note! This method cannot be called before initialize method has been triggered
 */
void bmGameAnalyticsAddErrorEvent(bmGameAnalyticsErrorSeverity severity, const char * message S3E_DEFAULT(NULL));

/*!
 @method

 @abstract Set 1st custom dimension

 @param dimension01
    One of the available dimension values set in configureAvailableCustomDimensions01<br>
    Will persist cross session. Set to nil to reset.

 @availability Available since 2.0.0

 @attribute Note! Must be called after setAvailableCustomDimensions01WithCustomDimensions
 */
void bmGameAnalyticsSetCustomDimension01(const char * dimension01);

void bmGameAnalyticsSetCustomDimension02(const char * dimension02);

void bmGameAnalyticsSetCustomDimension03(const char * dimension03);

/*!
 @method

 @abstract Set user facebook id

 @param facebookId
    Facebook id of user (Persists cross session)

 @availability Available since 2.0.0
 */
void bmGameAnalyticsSetUserFacebookId(const char * facebookId);

/*!
 @method

 @abstract Set user gender

 @param gender
    Gender of user (Persists cross session)<br>
    Must be one of (male / female)

 @availability Available since 2.0.0
 */
void bmGameAnalyticsSetUserGender(bool is_male S3E_DEFAULT(true));

/*!
 @method

 @abstract Set user birth year

 @param birthYear
    Birth year of user (Persists cross session)

 @availability Available since 2.0.0
 */
void bmGameAnalyticsSetUserBirthYear(int year);

// \cond HIDDEN_DEFINES
S3E_END_C_DECL
// \endcond



#endif /* !S3E_EXT_BMGAMEANALYTICS_H */
